# FROM node:20-alpine
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci
# COPY . .
# EXPOSE 5173
# CMD ["npm", "run", "dev"]

FROM node:20-alpine

# install openssl
RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
RUN npm ci

# copy everything & our entrypoint
COPY . .
COPY entrypoint.sh .

# use entrypoint.sh as the container’s start command
ENTRYPOINT ["./entrypoint.sh"]
