// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wudukirwsntbhfpmesbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZHVraXJ3c250YmhmcG1lc2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjU4MTUsImV4cCI6MjA2NDU0MTgxNX0.IEoVtk68JpdyMU85HN4LSQAczqQJLLmgpFCppCdZsxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);